name: Hello World Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - id: action
      uses: MauricioNTT/hello-action@main
      with: 
        message: Hello, inputs! 
    
    - run: echo ${{ steps.action.outputs.result }}
    
